version: "3.3"

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki
    logging:
      driver: none
    ports:
      - 3100:3100
    volumes:
      - ./conf/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail
    logging:
      driver: none
    ports:
      - 9080:9080
    volumes:
      - ./logs:/var/log
      - ./conf/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    logging:
      driver: none
    ports:
      - 3000:3000
