version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    network_mode: "host"
    ports:
      - "3100:3100"
    volumes:
      - ./conf/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    network_mode: "host"
    volumes:
      - ./logs:/var/log
      - ./conf/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "3000:3000"
    networks:
      - loki
