groups:
- name: node-up
  rules:
  - alert: node-up
    expr: up == 0
    for: 5s
    labels:
      severity: 1
      team: node
    annotations:
      summary: "{{$labels.instance}}Instance has been down for more than 15 seconds"
