version: '3.3'
services:

  zookeeper1:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper1
    ports:
      - "2181:2181"
    volumes:
#      - ./conf/zoo1.cfg:/conf/zoo.cfg
      - ./data/zoo1:/data
      - ./data/zoo1/datalog:/datalog
    environment:
      TZ: "Asia/Shanghai"
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.19.0.2

  zookeeper2:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper2
    ports:
      - "2182:2181"
    volumes:
#      - ./conf/zoo2.cfg:/conf/zoo.cfg
      - ./data/zoo2:/data
      - ./data/zoo2/datalog:/datalog
    environment:
      TZ: "Asia/Shanghai"
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.19.0.3

  zookeeper3:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper3
    ports:
      - "2183:2181"
    volumes:
#      - ./conf/zoo3.cfg:/conf/zoo.cfg
      - ./data/zoo3:/data
      - ./data/zoo3/datalog:/datalog
    environment:
      TZ: "Asia/Shanghai"
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      default:
        ipv4_address: 172.19.0.4

#network
networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
