version: '2'
services:

  zookeeper1:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper1
    ports:
      - "2181:2181"
    volumes:
      - ./conf/zoo1.cfg
      - ./data/zoo1:/data
      - ./data/zoo1/datalog:/datalog
    networks:
      zookeeper:
        ipv4_address: 172.19.0.2
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper2
    ports:
      - "2182:2181"
    volumes:
      - ./conf/zoo2.cfg
      - ./data/zoo2:/data
      - ./data/zoo2/datalog:/datalog
    networks:
      zookeeper:
        ipv4_address: 172.19.0.3
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper:3.7
#    restart: always
    container_name: zookeeper3
    ports:
      - "2183:2181"
    volumes:
      - ./conf/zoo3.cfg
      - ./data/zoo3:/data
      - ./data/zoo3/datalog:/datalog
    networks:
      zookeeper:
        ipv4_address: 172.19.0.4
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

#network
networks:
  zookeeper:
    ipam:
      config:
        - subnet: 172.19.0.0/16
