version: "3.3"
services:
  # database
  mysql:
    image: mysql:8.0
    container_name: db-mysql
    ports:
      - "3306:3306"
#    command:
#      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/user_data:/home/user_data
      - ./mysql/mysql-files:/var/lib/mysql-files/
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
#    networks:
#      common:
#        aliases:
#          - mysql
    network_mode: "host"

  # cache
  redis:
    container_name: db-redis
    image: redis:5.0
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
#    networks:
#      - common
    network_mode: "host"
    volumes:
      - ../tools/redis/data:/data
#      - ./redis/redis.conf:/etc/redis.conf

#network
#networks:
#  common:
#    external: true