version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    container_name: docker-zero
    volumes:
      - ./dgraph/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    container_name: docker-alpha
    volumes:
      - ./dgraph/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080
  ratel:
    image: dgraph/ratel:latest
    container_name: docker-ratel
    volumes:
      - ./dgraph/data:/dgraph
    ports:
      - 8000:8000
    network_mode: "host"