version: "3.2"
services:
  dgraph:
    image: dgraph/standalone:v20.11.2
    container_name: dgraph
    restart: always
    logging:
      driver: none
    volumes:
      - ./dgraph/data:/dgraph
      - /etc/localtime:/etc/localtime:ro #将外边时间直接挂载到容器内部，权限只读
      - /etc/timezone:/etc/timezone:ro #将外面的时间挂载到容器内部，权限只读，容器内不可修改
    ports:
      - 5080:5080
      - 6080:6080
      - 8080:8080
      - 9080:9080
      - 8000:8000
    command: /run.sh