version: "3.3"
services:
  #nginx
  nginx:
    image: nginx:1.19.9
    container_name: docker-nginx
    ports:
      - "80:80"
      - "443:443"
#    networks:
#      lnmp:
#        ipv4_address: 172.18.0.4
    network_mode: "host"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ../ssl:/ssl
      - ../../www:/usr/share/nginx/html
      - ../nginxDocker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginxDocker/conf/conf.d/:/etc/nginx/conf.d/:ro
#    links:
#      - php

  # php-fpm
  php:
    build: php
    container_name: docker-php
    ports:
      - "9000:9000"
    volumes:
      - ../www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:ro
      - ./php/php-fpm.d:/usr/local/etc/php/php-fpm.d
      - ../etc/hosts:/etc/hosts
    environment:
      TZ: "Asia/Shanghai"
#    networks:
#      lnmp:
#        ipv4_address: 172.18.0.5
    network_mode: "host"
#    links:
#      - mysql
#      - redis

#network
#networks:
#  lnmp:
#    ipam:
#      config:
#        - subnet: 172.18.0.0/16
