grpc.server.port=19080
spring.application.name=grpc-proxy
logging.file.path=./log
logging.level.root=INFO
#节点id：随机16位字符串，集群内唯一(grpc-proxy与data-synchronous服务同时部署时两个服务使用同一个node.id)
node.id=4EA34DF23F1740D1
#管控平台地址
server.ip=192.168.95.129
#kafka地址
kafka.ip=192.168.95.129:9092
#代理的dgraph数据库grpc地址
dgraph.service.info=${server.ip}:9080
#kafka组 主题配置
consumer.group-id=data-change-capture-${node.id}-${spring.application.name}
publish.config.topic=publish.config.topic
#send.log.topic值：cdc、log，log预留类型，未实现
send.log.topic=log
#kafka 生产者配置
spring.kafka.producer.bootstrap-servers=${kafka.ip}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.retries=3
#kafka 消费者配置
spring.kafka.consumer.bootstrap-servers=${kafka.ip}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=earliest