version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.2.3
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:8.2.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://localhost:9200" #设置访问elasticsearch的地址
    ports:
      - "5601:5601"
  logstash:
    image: logstash:8.2.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - "4560:4560"