server.port=19000
spring.application.name=data-synchronous
#节点id：随机16位字符串，集群内唯一(data-synchronous与grpc-proxy服务同时部署时两个服务使用同一个node.id)
node.id=4EA34DF23F1740D2
#管控平台地址
server.ip=192.168.92.234
#kafka地址
kafka.ip=192.168.95.129:9092
logging.file.path=./log
logging.level.root=INFO
#redis
spring.redis.password=0p9o8i7u6y5t4r3e2w1q
spring.redis.host=192.168.95.129
spring.redis.port=6379
spring.redis.database=1
#同步的dgraph数据库grpc地址
dgraph.service.info=${server.ip}:9080
#kafka组 主题配置
consumer.group-id=data-change-capture-${spring.application.name}-${node.id}
consumer.client-id=consumer-data-change-capture-${spring.application.name}-${node.id}
publish.config.topic=publish.config.topic
data.merge.topic=data.merge.topic
master.notice.topic=master.notice.topic
#send.log.topic值：cdc、log
send.log.topic=log
#kafka 生产者配置
spring.kafka.producer.bootstrap-servers=${kafka.ip}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.producer.retries=3
#kafka 消费者配置
spring.kafka.consumer.bootstrap-servers=${kafka.ip}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
#log读取目录，dgraph映射
#log.file.path=./cdcLog/sink.log
log.file.path=/Users/tanxianchen/coding/docker/dgraphDocker/data/cdcLog/sink.log