version: "3"
services:
  # database
  mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - "3306:3306"
    #    command:
    #      --lower_case_table_names=1
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/user_data:/home/user_data
      - ../mysql/mysql-files:/var/lib/mysql-files/
      - ../mysql/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      lnmp:
        ipv4_address: 172.18.0.2

  # cache
  redis:
    container_name: docker-redis
    image: redis:5.0
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      lnmp:
        ipv4_address: 172.18.0.3
    volumes:
      - ../redis/data:/data
  #      - ./redis/redis.conf:/etc/redis.conf

  golang:
    build: ../golang
    ports:
      - "8088:8088"
    links:
      - "mysql"
      - "redis"
    volumes:
      - $HOME/code/go:/go
    tty: true
    networks:
      lnmp:
        ipv4_address: 172.18.0.4