version: "3"
services:
  influxdb:
    image: influxdb:2.4.0-alpine
    container_name: influxdb
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data:/var/lib/influxdb
      - ./conf:/etc/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpwd
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=prometheuspwd
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf