version: "3.3"
services:
  redis:
    image: redis:5.0
    container_name: docker-redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
#    networks:
#      - common
#    network_mode: "host"
#    command:
#      --requirepass "123456"
    volumes:
      - ./redis/data:/data
#      - ./redis/redis.conf:/etc/redis/redis.conf

#  docker run -d --network host -e TZ=Asia/Shanghai -v /home/zhongtai/redis/data/:/data/ --restart=always --name redis redis:5.0.14 --requirepass 0p9o8i7u6y5t4r3e2w1q