version: "3.3"
services:
  redis:
    image: redis:5.0
    container_name: docker-redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Shanghai"
#    networks:
#      - common
#    network_mode: "host"
#    command:
#      --requirepass "123456"
    volumes:
      - ./redis/data:/data
#      - ./redis/redis.conf:/etc/redis.conf