version: '3.1'
services:
  tomcat:
#    restart: always
    image: tomcat:8.5.83-jre8
    container_name: tomcat
    logging:
      driver: none
    ports:
      - 8080:8080
      - 2280:2280
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./conf:/usr/local/tomcat/conf
      - ./bin:/usr/local/tomcat/bin
      - ./data:/data
    environment:
      TZ: Asia/Shanghai