version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    logging:
      driver: none
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/prometheus:/prometheus
      - ./conf/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.enable-lifecycle
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.time=7d
      - --storage.tsdb.retention.size=100MB
#      - --storage.tsdb.no-lockfile
#      - --storage.tsdb.wal-compression
#      - --rules.alert.resend-delay=5s
      - --web.listen-address=0.0.0.0:9099
#      - --query.timeout=2m
#      - --log.level=info
#      - --log.format=ogfmt

  monitor:
    image: monitor:master
    container_name: monitor
    logging:
      driver: none
    network_mode: "host"
    volumes:
      - ./conf/monitor:/usr/local/test/config
      - ./log:/usr/local/test/log

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    logging:
      driver: none
    hostname: influxdb
    network_mode: "host"
    volumes:
      - ./conf/influxdb:/etc/influxdb
      - ./data/influxdb/data:/var/lib/influxdb/data
    environment:
      - TZ=Asia/Shanghai
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpwd
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=prometheuspwd
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf

#
#  grafana:
#    container_name: grafana
#    image: grafana/grafana
#    ports:
#      - 3000:3000
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro

#  alertmanager:
#    container_name: alertmanager
#    image: prom/alertmanager:v0.24.0
#    ports:
#      - 9093:9093
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./conf/alertmanager:/etc/alertmanager

#  blackbox-exporter:
#    container_name: blackbox-exporter
#    image: prom/blackbox-exporter:v0.22.0
#    ports:
#      - 9115:9115
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./conf/blackbox-exporter:/etc/blackbox_exporter

#  prometheus-alert:
#    container_name: prometheus-alert
#    image: feiyu563/prometheus-alert:v4.8.2
#    ports:
#      - 8080:8080
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./conf/prometheus-alert:/app/conf