version: "3.2"
services:
  grpc-proxy:
    image: visionvera/grpc-proxy:0.0.1
    container_name: grpc-proxy
    restart: always
    logging:
      driver: none
    volumes:
      - ./config:/usr/local/test/config
      - ./cacheConfig:/usr/local/test/cacheConfig
      - ./logs:/usr/local/test/log
    ports:
      - "19080:19080"
      - "19081:19081"